name: Auto Merge vunk to develop

on:
  push:
    branches:
      - vunk  # Kích hoạt workflow khi có push lên nhánh vunk

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch toàn bộ lịch sử commit

      # Bước 2: Cấu hình Git
      - name: Configure Git
        run: |
          git config --global user.name "Khac Vu"
          git config --global user.email "khacvukt@gmail.com"

      # Bước 3: Merge nhánh vunk vào develop
      - name: Merge vunk into develop
        run: |
          git fetch origin develop
          git checkout develop
          git merge origin/vunk --no-ff --no-edit
          git push https://${{ secrets.KEY1213 }}@github.com/khacvukt/angular10.git develop