
name: Auto Create Pull Request from vunk to develop

on:
  push:
    branches:
      - feature/**  # Khi push lên nhánh vunk

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Pull Request from vunk to develop
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Tạo Pull Request từ vunk vào develop"
        body: "Pull request này được tạo tự động khi có push lên nhánh vunk."
        branch: vunk  # Nhánh vunk (nhánh bạn đang push lên)
        base: develop  # Nhánh develop (nơi bạn muốn merge vào)